package Interfaz;

import Clases.Empleado;
import Clases.Validar;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author keiss
 */
public class JDialog_Emple extends javax.swing.JDialog {
    
    static boolean añadir = false;
    static boolean modificar = false;
    static String rut;
    private Empleado cargarDatos(){
        Empleado emp = new Empleado();

        emp.setIdEmpleado(lbl_CodigoEmpleado.getText());
        emp.setNombre(this.txt_NombreEmpleado.getText());
        emp.setApellidoP(this.txt_ApellidoPEmpleado.getText());
        emp.setApellidoM(this.txt_ApellidoMEmpleado.getText());
        emp.setRut(rut);
        emp.setContraseña(this.txtpass_Contraseña1Empleado.getText());
        emp.setTipo(cmb_TipoEmpleado.getSelectedItem().toString());
        
        return emp;
    }
    
    private void iniciarComponentes(){
        txt_NombreEmpleado.requestFocus();
        
        if (añadir)
            setTitle("Agregar Empleado - SpeedeX");
        else
            setTitle("Modificar Empleado - SpeedeX");

        this.setLocationRelativeTo(null); //Centrar el JFrame al centro de la pantalla
        setIconImage(new ImageIcon(getClass().getResource("/Complementos/Logo Speedex2.png")).getImage()); // Icono del programa
        this.setResizable(false);
        setSize(824, 510); 
        
        lbl_Ingresar.setVisible(false);
        lbl_Modificar.setVisible(false);
        
        cmb_TipoEmpleado.removeAllItems();
        cmb_TipoEmpleado.addItem("Empleado");
        cmb_TipoEmpleado.addItem("Administrador");
        cmb_TipoEmpleado.addItem("Inhabilitado");
    
    }

    public JDialog_Emple(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        añadir = true;
        iniciarComponentes();
        
        Empleado emp = new Empleado();
        
        lbl_Ingresar.setVisible(true);
        lbl_CodigoEmpleado.setText(String.valueOf(Integer.parseInt(emp.obtenerCodigo().getIdEmpleado()) + 1)); //Obtiene el codigo y le suma 1
    }
    
    public JDialog_Emple(java.awt.Frame parent, boolean modal, Empleado emp) {
        super(parent, modal);
        initComponents();
        
        iniciarComponentes();
        
        Empleado Emp = emp;
        
        modificar = true;
        
        lbl_CodigoEmpleado.setText(Emp.getIdEmpleado());
        txt_NombreEmpleado.setText(Emp.getNombre());
        txt_ApellidoPEmpleado.setText(Emp.getApellidoP());
        txt_ApellidoMEmpleado.setText(Emp.getApellidoM());
        txt_RutEmpleado.setText(Emp.getRut());
        
        int tipo = 0;
                
        if (Emp.getTipo().equals("Administrador")) 
            tipo = 1;
        else if (Emp.getTipo().equals("Inhabilitado"))
            tipo = 2;
        
        cmb_TipoEmpleado.setSelectedIndex(tipo);
        
        lbl_Modificar.setVisible(true);
        
        txt_RutEmpleado.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_CodigoEmpleado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmb_TipoEmpleado = new javax.swing.JComboBox<>();
        txt_NombreEmpleado = new javax.swing.JTextField();
        txt_ApellidoPEmpleado = new javax.swing.JTextField();
        txt_ApellidoMEmpleado = new javax.swing.JTextField();
        txt_RutEmpleado = new javax.swing.JTextField();
        txtpass_Contraseña1Empleado = new javax.swing.JPasswordField();
        txtpass_Contraseña2Empleado = new javax.swing.JPasswordField();
        btn_LimpiarNombre = new javax.swing.JButton();
        lbl_Modificar = new javax.swing.JLabel();
        lbl_Ingresar = new javax.swing.JLabel();
        btn_Volver = new javax.swing.JButton();
        btn_Aceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/Rut.png"))); // NOI18N
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(460, 50, 41, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/Nombre.png"))); // NOI18N
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(120, 100, 90, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/ApellidoP.png"))); // NOI18N
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(60, 140, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/ApellidoM.png"))); // NOI18N
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(60, 190, 140, 30);

        lbl_CodigoEmpleado.setForeground(new java.awt.Color(0, 204, 204));
        lbl_CodigoEmpleado.setText("------");
        jLayeredPane1.add(lbl_CodigoEmpleado);
        lbl_CodigoEmpleado.setBounds(240, 50, 110, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/Codigo.png"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(140, 50, 60, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/Contraseña.png"))); // NOI18N
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(410, 150, 100, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/Tipo.png"))); // NOI18N
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(460, 190, 45, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/Contraseña.png"))); // NOI18N
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(410, 100, 100, 30);

        cmb_TipoEmpleado.setForeground(new java.awt.Color(0, 204, 204));
        cmb_TipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_TipoEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane1.add(cmb_TipoEmpleado);
        cmb_TipoEmpleado.setBounds(540, 200, 130, 30);

        txt_NombreEmpleado.setForeground(new java.awt.Color(0, 153, 153));
        txt_NombreEmpleado.setSelectionColor(new java.awt.Color(255, 153, 51));
        txt_NombreEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NombreEmpleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreEmpleadoKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txt_NombreEmpleado);
        txt_NombreEmpleado.setBounds(220, 90, 130, 30);

        txt_ApellidoPEmpleado.setForeground(new java.awt.Color(0, 153, 153));
        txt_ApellidoPEmpleado.setSelectionColor(new java.awt.Color(255, 153, 51));
        txt_ApellidoPEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ApellidoPEmpleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidoPEmpleadoKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txt_ApellidoPEmpleado);
        txt_ApellidoPEmpleado.setBounds(220, 140, 130, 30);

        txt_ApellidoMEmpleado.setForeground(new java.awt.Color(0, 153, 153));
        txt_ApellidoMEmpleado.setSelectionColor(new java.awt.Color(255, 153, 51));
        txt_ApellidoMEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ApellidoMEmpleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidoMEmpleadoKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txt_ApellidoMEmpleado);
        txt_ApellidoMEmpleado.setBounds(220, 190, 130, 30);

        txt_RutEmpleado.setForeground(new java.awt.Color(0, 153, 153));
        txt_RutEmpleado.setSelectionColor(new java.awt.Color(255, 153, 51));
        txt_RutEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_RutEmpleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RutEmpleadoKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txt_RutEmpleado);
        txt_RutEmpleado.setBounds(540, 50, 130, 30);

        txtpass_Contraseña1Empleado.setForeground(new java.awt.Color(0, 153, 153));
        txtpass_Contraseña1Empleado.setSelectionColor(new java.awt.Color(255, 153, 51));
        txtpass_Contraseña1Empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpass_Contraseña1EmpleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpass_Contraseña1EmpleadoKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtpass_Contraseña1Empleado);
        txtpass_Contraseña1Empleado.setBounds(540, 100, 130, 30);

        txtpass_Contraseña2Empleado.setForeground(new java.awt.Color(0, 153, 153));
        txtpass_Contraseña2Empleado.setSelectionColor(new java.awt.Color(255, 153, 51));
        txtpass_Contraseña2Empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpass_Contraseña2EmpleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpass_Contraseña2EmpleadoKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtpass_Contraseña2Empleado);
        txtpass_Contraseña2Empleado.setBounds(540, 150, 130, 30);

        btn_LimpiarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Boton Limpiar.png"))); // NOI18N
        btn_LimpiarNombre.setBorder(null);
        btn_LimpiarNombre.setBorderPainted(false);
        btn_LimpiarNombre.setContentAreaFilled(false);
        btn_LimpiarNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_LimpiarNombre.setFocusPainted(false);
        btn_LimpiarNombre.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Boton Limpiar Press.png"))); // NOI18N
        btn_LimpiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarNombreActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btn_LimpiarNombre);
        btn_LimpiarNombre.setBounds(690, 230, 40, 30);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 750, 280));

        lbl_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/Modificar Empleado.png"))); // NOI18N
        getContentPane().add(lbl_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbl_Ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Textos/Ingresar Empleado.png"))); // NOI18N
        getContentPane().add(lbl_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btn_Volver.setForeground(new java.awt.Color(255, 51, 51));
        btn_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Boton Volver.png"))); // NOI18N
        btn_Volver.setBorderPainted(false);
        btn_Volver.setContentAreaFilled(false);
        btn_Volver.setFocusPainted(false);
        btn_Volver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Boton Volver Press.png"))); // NOI18N
        btn_Volver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Boton Volver Mouse.png"))); // NOI18N
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 80, 60));

        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Boton Aceptar.png"))); // NOI18N
        btn_Aceptar.setBorder(null);
        btn_Aceptar.setBorderPainted(false);
        btn_Aceptar.setContentAreaFilled(false);
        btn_Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Aceptar.setFocusPainted(false);
        btn_Aceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Boton Aceptar Press2.png"))); // NOI18N
        btn_Aceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Boton Aceptar Mouse.png"))); // NOI18N
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 170, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Logo Speedex Mini4.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/Fondo Proceso.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LimpiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarNombreActionPerformed
        limpiar();
    }//GEN-LAST:event_btn_LimpiarNombreActionPerformed
     private void limpiar(){
        this.txt_NombreEmpleado.setText("");
        this.txt_ApellidoPEmpleado.setText("");
        this.txt_ApellidoMEmpleado.setText("");
        this.txt_RutEmpleado.setText("");
        this.txtpass_Contraseña1Empleado.setText("");
        this.txtpass_Contraseña2Empleado.setText("");
    }
    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        añadir = false;
        modificar = false;
        this.setVisible(false);
    }//GEN-LAST:event_btn_VolverActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        Validar v = new Validar();
        if (!v.campoVacio(txt_RutEmpleado.getText()) && !v.campoVacio(txt_NombreEmpleado.getText()) && !v.campoVacio(txt_ApellidoPEmpleado.getText()) && !v.campoVacio(txtpass_Contraseña1Empleado.getText()) && !v.campoVacio(txtpass_Contraseña2Empleado.getText())) {
            if (añadir) 
                añadirEmpleado();
            else if (modificar) 
                modificarEmpleado(); 
        }
        else
            JOptionPane.showMessageDialog(null, "Los campos no pueden quedar vacíos.","Cuidado!",JOptionPane.WARNING_MESSAGE);
             
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_NombreEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreEmpleadoKeyTyped
        Validar v = new Validar();       
        if (!v.maximoLargo(txt_NombreEmpleado.getText(), 20))
            evt.consume();

        if(Character.isDigit(evt.getKeyChar())) 
            evt.consume(); 
    }//GEN-LAST:event_txt_NombreEmpleadoKeyTyped

    private void txt_ApellidoPEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoPEmpleadoKeyTyped
        Validar v = new Validar();       
        if (!v.maximoLargo(txt_ApellidoPEmpleado.getText(), 30))
            evt.consume();

        if(Character.isDigit(evt.getKeyChar())) 
            evt.consume(); 
    }//GEN-LAST:event_txt_ApellidoPEmpleadoKeyTyped

    private void txt_ApellidoMEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoMEmpleadoKeyTyped
        Validar v = new Validar();       
        if (!v.maximoLargo(txt_ApellidoMEmpleado.getText(), 30))
            evt.consume();

        if(Character.isDigit(evt.getKeyChar())) 
            evt.consume(); 
    }//GEN-LAST:event_txt_ApellidoMEmpleadoKeyTyped

    private void txt_RutEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RutEmpleadoKeyTyped
        Validar v = new Validar();       
        if (!v.maximoLargo(txt_ApellidoMEmpleado.getText(), 10))
            evt.consume();
    }//GEN-LAST:event_txt_RutEmpleadoKeyTyped

    private void txtpass_Contraseña1EmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpass_Contraseña1EmpleadoKeyTyped
        Validar v = new Validar();       
        if (!v.maximoLargo(txt_ApellidoMEmpleado.getText(), 20))
            evt.consume();
    }//GEN-LAST:event_txtpass_Contraseña1EmpleadoKeyTyped

    private void txtpass_Contraseña2EmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpass_Contraseña2EmpleadoKeyTyped
        Validar v = new Validar();       
        if (!v.maximoLargo(txt_ApellidoMEmpleado.getText(), 10))
            evt.consume();
    }//GEN-LAST:event_txtpass_Contraseña2EmpleadoKeyTyped

    private void txt_NombreEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreEmpleadoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && añadir)
            añadirEmpleado();
        else if(evt.getKeyCode() == KeyEvent.VK_ENTER && modificar)
            modificarEmpleado();
    }//GEN-LAST:event_txt_NombreEmpleadoKeyPressed

    private void txt_ApellidoPEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoPEmpleadoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && añadir)
            añadirEmpleado();
        else if(evt.getKeyCode() == KeyEvent.VK_ENTER && modificar)
            modificarEmpleado();
    }//GEN-LAST:event_txt_ApellidoPEmpleadoKeyPressed

    private void txt_ApellidoMEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoMEmpleadoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && añadir)
            añadirEmpleado();
        else if(evt.getKeyCode() == KeyEvent.VK_ENTER && modificar)
            modificarEmpleado();
    }//GEN-LAST:event_txt_ApellidoMEmpleadoKeyPressed

    private void txt_RutEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RutEmpleadoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && añadir)
            añadirEmpleado();
        else if(evt.getKeyCode() == KeyEvent.VK_ENTER && modificar)
            modificarEmpleado();
    }//GEN-LAST:event_txt_RutEmpleadoKeyPressed

    private void txtpass_Contraseña1EmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpass_Contraseña1EmpleadoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && añadir)
            añadirEmpleado();
        else if(evt.getKeyCode() == KeyEvent.VK_ENTER && modificar)
            modificarEmpleado();
    }//GEN-LAST:event_txtpass_Contraseña1EmpleadoKeyPressed

    private void txtpass_Contraseña2EmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpass_Contraseña2EmpleadoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && añadir)
            añadirEmpleado();
        else if(evt.getKeyCode() == KeyEvent.VK_ENTER && modificar)
            modificarEmpleado();
    }//GEN-LAST:event_txtpass_Contraseña2EmpleadoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_Emple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_Emple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_Emple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_Emple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_Emple dialog = new JDialog_Emple(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_LimpiarNombre;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JComboBox<String> cmb_TipoEmpleado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbl_CodigoEmpleado;
    private javax.swing.JLabel lbl_Ingresar;
    private javax.swing.JLabel lbl_Modificar;
    private javax.swing.JTextField txt_ApellidoMEmpleado;
    private javax.swing.JTextField txt_ApellidoPEmpleado;
    private javax.swing.JTextField txt_NombreEmpleado;
    private javax.swing.JTextField txt_RutEmpleado;
    private javax.swing.JPasswordField txtpass_Contraseña1Empleado;
    private javax.swing.JPasswordField txtpass_Contraseña2Empleado;
    // End of variables declaration//GEN-END:variables

    private void añadirEmpleado() {
        Empleado emp;
        Validar v = new Validar();
        if (txtpass_Contraseña1Empleado.getText().equals(txtpass_Contraseña2Empleado.getText())) {

                rut = v.validarRut(txt_RutEmpleado.getText());

                if (rut == null)
                    JOptionPane.showMessageDialog(null, "Rur inválido, favor revísarlo.","Precaución.",JOptionPane.WARNING_MESSAGE);

                else{
                    emp = cargarDatos();

                    if(emp.insertarEmpleado()){
                        JOptionPane.showMessageDialog(null, "El cliente "+emp.getNombre()+" fue añadido correctamente.","Cliente ingresado",JOptionPane.INFORMATION_MESSAGE);
                        this.lbl_CodigoEmpleado.setText(String.valueOf(Integer.parseInt(this.lbl_CodigoEmpleado.getText()) + 1)); //Actualiza el lblId
                        limpiar();
                    }
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Contraseñas no coinciden!.","Favor verifica la contraseña.",JOptionPane.WARNING_MESSAGE);
    }

    private void modificarEmpleado() {
        Empleado emp = cargarDatos();

        if (emp.actualizarEmpleado())
            JOptionPane.showMessageDialog(null, "Datos editados correctamente.","Datos empleado editados",JOptionPane.INFORMATION_MESSAGE);
    }
}
