package Interfaz;

import Clases.Empleado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * @author Keyss
 */
public class TablaPrueba extends javax.swing.JFrame {

    /**
     * Creates new form TablaPrueba
     */
    
    public TablaPrueba() {
        initComponents();
        
        Empleado emp = new Empleado();
        ArrayList <Empleado> cargarDatosEmpleado = new ArrayList();
        
        //cargarDatosEmpleado = emp.buscarDatosEmpleado();
        
        if (cargarDatosEmpleado == null || cargarDatosEmpleado.size() == 0) 
            JOptionPane.showMessageDialog(null, "No se encontro ningún dato o aún no tiene ningún empleado.","Información!",JOptionPane.INFORMATION_MESSAGE);
        else{
            DefaultTableCellRenderer Alinear = new DefaultTableCellRenderer();
            Alinear.setHorizontalAlignment(SwingConstants.CENTER);//alinea  en el centro datos de la tabla 
            DefaultTableModel modelo = (DefaultTableModel)tb_ConsultaEmpleado.getModel();
            
//            for (int i = tb_ConsultaEmpleado.getRowCount() -1; i >= 0; i--)
//                modelo.removeRow(i); 
        
            for (int i = 0; i < 6; i++) 
                tb_ConsultaEmpleado.getColumnModel().getColumn(i).setCellRenderer(Alinear); //llama a centrar los dtos de las columnas de la tabla
            
            //datos que se cargaran en la tabla
            Object[] fila = new Object[modelo.getColumnCount()];
            
            for (int i = 0; i <cargarDatosEmpleado.size(); i++) {

                fila[0]=cargarDatosEmpleado.get(i).getIdEmpleado();            
                fila[1]=cargarDatosEmpleado.get(i).getNombre();
                fila[2]=cargarDatosEmpleado.get(i).getApellidoP();
                fila[3]=cargarDatosEmpleado.get(i).getApellidoM();
                fila[4]=cargarDatosEmpleado.get(i).getRut();
                //fila[5]=cargarDatosEmpleado.get(i).getContraseña();
                fila[5]=cargarDatosEmpleado.get(i).getTipo();

                modelo.addRow(fila);
            }  
                
            tb_ConsultaEmpleado.setModel(modelo);

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tb_ConsultaEmpleado = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txt_busca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_ConsultaEmpleado.setBackground(new java.awt.Color(0, 204, 204));
        tb_ConsultaEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tb_ConsultaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido P", "Apellido M", "Rut", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_ConsultaEmpleado.setGridColor(new java.awt.Color(0, 102, 102));
        tb_ConsultaEmpleado.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tb_ConsultaEmpleado.setSelectionForeground(new java.awt.Color(0, 51, 51));
        jScrollPane2.setViewportView(tb_ConsultaEmpleado);

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscaActionPerformed(evt);
            }
        });
        txt_busca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int filaseleccionada = tb_ConsultaEmpleado.getSelectedRow();
        Empleado emp = new Empleado();
        
        if (filaseleccionada >= 0) {

            emp.setIdEmpleado(tb_ConsultaEmpleado.getValueAt(filaseleccionada, 0).toString()); //getValueAt ob tiene el valor de la fila
            emp.setNombre(tb_ConsultaEmpleado.getValueAt(filaseleccionada, 1).toString());
            emp.setApellidoP(tb_ConsultaEmpleado.getValueAt(filaseleccionada, 2).toString());
            emp.setApellidoM(tb_ConsultaEmpleado.getValueAt(filaseleccionada, 3).toString());
            emp.setRut(tb_ConsultaEmpleado.getValueAt(filaseleccionada, 4).toString());
            emp.setTipo(tb_ConsultaEmpleado.getValueAt(filaseleccionada, 5).toString());
            
            Seleccion select = new Seleccion(emp);
            select.setVisible(true);
            this.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningún empleado.","Seleccione empleado",JOptionPane.INFORMATION_MESSAGE);    
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_buscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscaKeyTyped
        //JOptionPane.showMessageDialog(null, "Holaa.","Seleccione empleado",JOptionPane.INFORMATION_MESSAGE);    
    }//GEN-LAST:event_txt_buscaKeyTyped

    private void txt_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscaActionPerformed
        if (!this.txt_busca.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Holaa.","Seleccione empleado",JOptionPane.INFORMATION_MESSAGE);    
        }
    }//GEN-LAST:event_txt_buscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_ConsultaEmpleado;
    private javax.swing.JTextField txt_busca;
    // End of variables declaration//GEN-END:variables
}
